name: Flutter Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Release APK
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Display Flutter version
        run: flutter --version

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Setup environment variables
        run: cp .env.example .env

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: whatamilookingat-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7

      - name: Update Latest Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Development Build
          body: "Automated build from the latest commit on the main branch."
          files: build/app/outputs/flutter-apk/app-release.apk
          prerelease: true
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
